### ISSUE TITLE
Docker Packaging Script Needed

### ISSUE THREAD

**Issue by vinnnyr** [ros-agriculture/lawn_tractor#16]
Currently the `start.sh` does not match what is built in the `Dockerfile` . We need to create a packaging script that automatically pushes to dockerhub,

**Comment by droter** [comment]
When building the Dockerfile after cloning the repository I get this message:

lawn_tractor/docker$ ./build.sh 
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/matt/ros/tractorsim_ws/lawn_tractor_pr/lawn_tractor/docker/Dockerfile: no such file or directory
Fix:  Move build.sh to root dir.

The container fails to build with the message:
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
lawn_tractor_navigation: Cannot locate rosdep definition for [geonav_transform]
The command '/bin/sh -c rosdep update &&     rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO} --as-root=apt:false &&     apt-get -qq upgrade &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by vinnnyr** [comment]
### RE: Build Script
 I imagined the user to run the script from the root directory. I will improve the documentation. 

Example:
`vinny@pop-os:~/Code/lawn_tractor_ws/src$ ./docker/build.sh`

### RE: Container Build Failure
I am not able to replicate but I have the feeling that was caused by not initializing the submodule before building. 
I should add in the instructions or in the build script:
`git submodule update --init --recursive`
